### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Deadly-Bytes** [meldsza/log-to-discord#1]
I see that this is a bit old and maybe that's what its not working anymore. This is the error I'm getting trying to run it

`:/opt/scripts/log-to-discord$ node index.js
(node:6707) UnhandledPromiseRejectionWarning: StatusCodeError: 400 - "{\"_misc\": [\"Expected \\\"Content-Type\\\" header to be one of {'application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'}.\"]}"
    at new StatusCodeError (/opt/scripts/log-to-discord/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/opt/scripts/log-to-discord/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/opt/scripts/log-to-discord/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/opt/scripts/log-to-discord/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/opt/scripts/log-to-discord/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/opt/scripts/log-to-discord/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
(node:6707) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6707) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

Not sure if you are interested in updating this or if the issues is something else. Thanks for making this and if you want someone to debug some new code, let me know.

**Comment by meldsza** [comment]
This issue occured due to the changes in the discord API and now has been fixed. Thank you for bringing it to my notice. Sorry about the delay
